### ISSUE TITLE
is Debian aarch64 supported?

### ISSUE THREAD

**Issue by xiechunge** [Netis/packet-agent#124]
hi 

In releases
I only find https://github.com/Netis/packet-agent/releases/download/v0.6.0/netis-packet-agent-0.6.0_amd64.deb yet

is Debian aarch64 supported?

thanks

**Comment by vaderyang** [comment]
> hi
> 
> In releases I only find https://github.com/Netis/packet-agent/releases/download/v0.6.0/netis-packet-agent-0.6.0_amd64.deb yet
> 
> is Debian aarch64 supported?
> 
> thanks

not in the plan yet. Which hardware platform will you install onto?

**Comment by xiechunge** [comment]
Debian GNU/Linux 11
aarch64

I try compile it on this hardware platform 
is it ok?

**Comment by vaderyang** [comment]
> Debian GNU/Linux 11 aarch64
> 
> I try compile it on this hardware platform is it ok?

let me know what happened, thank you.

**Comment by xiechunge** [comment]
I want to install the packet Agent on debian(aarch64 platform)
I had not find the Installation package，so i compiled it on my debian

But error occured below
![image](https://github.com/Netis/packet-agent/assets/20079886/36a92d0e-fa9d-4f8f-ac1d-ed596035dda0)

How I solve it ？And I want to confirm if the agent can run on debian(arm)

thank you

**Comment by robbietu** [comment]
it can be an issue on aarch64 which is not supported yest
