### ISSUE TITLE
pktminerg on windows platform

### ISSUE THREAD

**Issue by xiechunge** [Netis/packet-agent#126]
hello,

I use pktminerg with the command below on windows platform,but it has error

how can i use the pktminerg with options "-i"?

PS C:\Users\Administrator\bin> **getmac /fo csv /v**
"连接名","网络适配器","物理地址","传输名称"
"VirtualNet","Hillstone Virtual Network Adapter Tunnel","暂缺","媒体已断开连接"
"本地连接","Xen Net Device Driver","FA-16-3E-A3-F9-11","\Device\Tcpip_{6E118FB8-ED1B-48C4-B597-EC9E2560CC2A}"
PS C:\Users\Administrator\bin>
PS C:\Users\Administrator\bin>
PS C:\Users\Administrator\bin> **.\pktminerg.exe -i \Device\NPF_{6E118FB8-ED1B-48C4-B597-EC9E2560CC2A} -r 192.168.1.20**
pktminerg.exe : 为 -inputFormat 参数指定了无效的值(\Device\NPF_)。有效值为 Text 和 Xml。
所在位置 行:1 字符: 1
+ .\pktminerg.exe -i \Device\NPF_{6E118FB8-ED1B-48C4-B597-EC9E2560CC2A} -r 192.168 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) []，ParameterBindingException
    + FullyQualifiedErrorId : IncorrectValueForFormatParameter

PS C:\Users\Administrator\bin>

thank you for your help

**Comment by robbietu** [comment]
As we mentioned in guide, on windows, the command should be like .\pktminerg.exe "-i ethernet -r 10.1.1.1 -k 12". The name of  the network interface should be followed with "-i" (not the serials in your command,), and all the parameters of the device should be in the " ". If you want to capture the traffic on different network interface, several group of parameters could be followed, each group is for one device and within a couple of "".

**Comment by xiechunge** [comment]
Thank you very much for your reply
 
I had tried to use "" and it is ok such as the log “start pcap snoop” below,but it not capture traffic.
In wireshark I can see the data on the device "\Device\NPF_{6E118FB8-ED1B-48C4-B597-EC9E2560CC2A}"
![c62487ae2a00cbede45bc12807f0486](https://github.com/Netis/packet-agent/assets/20079886/4fb49c8a-d159-4883-86bf-c23742eed300)


On the windows platform ,is there anything I need to pay attention to

**Comment by robbietu** [comment]
On Windows,no logs will be printed when capture traffic. So please observe if traffic is forwarded to 192.168.1.20 (according to your command). By the way, please use the latest version of Packet-agent to avoid any bugs existed in previous versions and fixed in the latest one.

**Comment by xiechunge** [comment]
OK ,
Thanks

I see the Remarks "Make sure the firewall allows GRE packets to be sent to the target".

On the windows platform, I also do not to do it?

**Comment by robbietu** [comment]
At first, I think that you can observe if there is any traffic to your target on your windows server. If yes, the issue is caused by the firewall.

**Comment by xiechunge** [comment]
hi,

I had the result that on my windows I can not capture the gre packets with wireshark while I had turn off the firewall.
And I can not caputre the gre packets on the remote devices(192.168.1.20).

I think it can not encapsulate them with GRE on the windows platform.
I have no other ideas.


Thanks

**Comment by robbietu** [comment]
As I said， in the command of pktminerg, it should be the name of the network interface followed by "-i" ,not "\Device\NPF_{6E118FB8-ED1B-48C4-B597-EC9E2560CC2A}"

**Comment by xiechunge** [comment]
The document document that On Windows platform, you must use NIC's NT Device Name with format "\Device\NPF_{UUID}" as interface param.

![image](https://github.com/Netis/packet-agent/assets/20079886/daed9ebf-85c9-4b46-a64d-6252a24b0026)

You mean I do not need to follow this?

**Comment by robbietu** [comment]
now, we should use the name of network interface and I will update the doc

**Comment by xiechunge** [comment]
OK,
If the network interface name has space,such as "WLAN 2",it is ok?

Now, i use the name below,i can not caputre the gre traffic on the windows.

![image](https://github.com/Netis/packet-agent/assets/20079886/24ddd8af-47f5-4796-8960-ea501bf5abf3)

**Comment by robbietu** [comment]
Your command is right. And to debug the issue, please check if there is any traffic on the network interface "WALN 2".  After that, you can observer, on your windows server,  if the traffic is forwarded to the target.

**Comment by xiechunge** [comment]
Yes, i did it like you say.
First ,there is any traffic on the interface "WLAN 2". But i can not see the traffic is forwarded to the target with GRE encapsulated.
![image](https://github.com/Netis/packet-agent/assets/20079886/9aa2b3d3-1bc1-42e1-b0c2-786e0ffc209d)

What else should I do？（I have already closed the firewall）

**Comment by robbietu** [comment]
I find that, in your command, it is "WALN" not "WLAN"

**Comment by xiechunge** [comment]
Yes,
Sorry, it is my fault,
Now it is ok while i change it to "WLAN 2"

thanks

**Comment by xiechunge** [comment]
I had a new qustion,

In the ncloud, i use pktminerg to forwarded traffic from windows server to linux,
i can see the gre data on the windows,but i can not caputure the gre data on the linux.
![image](https://github.com/Netis/packet-agent/assets/20079886/22116e23-99bc-430b-82a3-586e61ad6ff0)
![image](https://github.com/Netis/packet-agent/assets/20079886/c6e93882-2a2a-41f3-bd4e-ab61d528c22e)

**Comment by robbietu** [comment]
That packets with GRE encasulated have been observed on windows server means that PA works well. As to why they aren't routed to the dest server(linux), it should be an issue related to your network. sorry, I have no idea about that.
