### ISSUE TITLE
how to install through yum command?

### ISSUE THREAD

**Issue by vaderyang** [Netis/packet-agent#60]
any idea about simplified installation steps, add repository to use yum install/upgrade command?

**Comment by jacknetis** [comment]
We had some investigation about adding packet-agent to public repository before. The conclusion is it's hard for us to do that. Some communities use the rule "Don't call us, we will call you", which means they will collect the packages by themselves. Some set high standard to approve the merge request, Fedora for example: https://fedoraproject.org/wiki/Join_the_package_collection_maintainers

**Comment by vaderyang** [comment]
any idea about a customized repo to be added into yum command like https://www.thegeekdiary.com/centos-rhel-how-to-create-and-host-yum-repository-over-httpd/

**Comment by jacknetis** [comment]
We investigated and talked about the customized repo before. We thought it will not simplify the steps for users, as they need to import and refresh repo first and then use yum command to install packet agent. Also, hosting the repo will increase the burden of mantaining servers and services.
