### ISSUE TITLE
packet-agent adds timestamp before output pcaps

### ISSUE THREAD

**Issue by longxu-sd** [Netis/packet-agent#63]
I hope that packet-agent adds timestamp(with ns), before output pcap.

**Comment by lcywoodlucy** [comment]
We plan to support timestamp by [ERSPAN marker packet interval](https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/sw/7-x/system_management/configuration/guide/b_Cisco_Nexus_9000_Series_NX-OS_System_Management_Configuration_Guide_7x/b_Cisco_Nexus_9000_Series_NX-OS_System_Management_Configuration_Guide_7x_chapter_010001.html#concept_1B9C293BD37647438BA18C34E330E490).

**Comment by longxu-sd** [comment]
ERSPAN looks like supported by Cisco switch. If customer uses Cloud, it will be double GRE head before real packet(one added by pkt-agent, another added by Cloud platform). If you use some switch function to support timestamp, it will be written in the first GRE head, and will be dismantled by Cloud platform before sending it to BPC.

My proposal is support timestamp in real packet. Then BPC can use it directly.

**Comment by vaderyang** [comment]
ERSPAN is good, packing timestamp in real packet is another method e.g. VSS
Monitoring tap can add a packet trail for additional information.
I believe BPC can support ERSPAN as well
