### ISSUE TITLE
Capture on an interface with no ip address

### ISSUE THREAD

**Issue by lhrollin** [Netis/packet-agent#64]
When I run "pktminerg -i tap7f7776ea-11 -r 10.0.0.222" to capture on interface tap7f7776ea-11, I get:

> [2019-10-25 17:07:36] Set pcap filter as "not host 10.0.0.222".
> [2019-10-25 17:07:36]  Call pcap_lookupnet failed, error is tap7f7776ea-11: no IPv4 address assigned.
> [2019-10-25 17:07:36] Call PcapLiveHandler openPcap failed.

But I do need to capture on interface "tap7f7776ea-11", which is a virtual interface on linux-bridge, and send the packets via another interface to host "10.0.0.222", please kindly suggest a solution, thank you.

**Comment by lcywoodlucy** [comment]
You can use --nofilter to ignore default filter, and use -B to bind  another interface which send  packet to "10.0.0.222",

**Comment by lhrollin** [comment]
It works, thank you!
