### ISSUE TITLE
can i use a non-root user to executive packet-agent ?

### ISSUE THREAD

**Issue by 7m24** [Netis/packet-agent#70]
can i use a non-root user to executive packet-agent ?

**Comment by lcywoodlucy** [comment]
- Setting network privileges for pktminerg if your kernel and file system support file capabilities

1. Ensure that you have installed the necessary tools, such as the setcap command.
2. sudo setcap cap_net_raw,cap_net_admin+eip /usr/local/bin/pktminerg 
3. Start Wireshark as non-root and ensure you see the list of interfaces and can do live capture.

- Setting network privileges for pktminerg if your kernel and file system don't support file capabilities，In this case, you will need to make pktminerg set-UID to root.

1. chown root /usr/local/bin/pktminerg
2. chmod u+s /usr/local/bin/pktminerg

**Comment by 7m24** [comment]
> * Setting network privileges for pktminerg if your kernel and file system support file capabilities
> 
> 1. Ensure that you have installed the necessary tools, such as the setcap command.
> 2. sudo setcap cap_net_raw,cap_net_admin+eip /usr/local/bin/pktminerg
> 3. Start Wireshark as non-root and ensure you see the list of interfaces and can do live capture.
> 
> * Setting network privileges for pktminerg if your kernel and file system don't support file capabilities，In this case, you will need to make pktminerg set-UID to root.
> 
> 1. chown root /usr/local/bin/pktminerg
> 2. chmod u+s /usr/local/bin/pktminerg

Great Thanks！
