### ISSUE TITLE
简单用tomcat自带服务测试了下，发现能承受的qps并不高

### ISSUE THREAD

**Issue by superscari** [Netis/packet-agent#75]
catch-analysis transport protocal maybe not proper

**Comment by radiolover** [comment]
能否详细描述一下现象？packet-agent是基于libpcap的网卡抓包工具，理想情况下高达1Gbps不丢包。

**Comment by superscari** [comment]
猜测应该是端口镜像限制了传输性能

**Comment by vaderyang** [comment]
可能可以考虑配置两个虚拟网卡？

**Comment by huangh901218** [comment]
> 能否详细描述一下现象？packet-agent是基于libpcap的网卡抓包工具，理想情况下高达1Gbps不丢包。

libpcap的抓包性能没有那么高吧！1Gbps肯定达到，不知道是否对libpcap做了改造
