### ISSUE TITLE
请问支持vs2017编译么？

### ISSUE THREAD

**Issue by muse117** [Netis/packet-agent#83]
您好，我下载了源码，用vs2017尝试编译，boost版本是1.73，cmake配置没有成功是因为boost版本不匹配么？

**Comment by lcywoodlucy** [comment]
支持vs2017，boost版本建议改成1.69

**Comment by muse117** [comment]
> 支持vs2017，boost版本建议改成1.69

我对您的项目很感兴趣，请问有交流的技术群么？

**Comment by muse117** [comment]
> 支持vs2017，boost版本建议改成1.69

用vs2017，boost编译成功了，另外一个问题是，如果几百台资产同时部署的话，网络带宽会遇到问题么？需要考虑数据压缩的问题么？

**Comment by lcywoodlucy** [comment]
几百台同时部署的话有可能会出现丢包的情况，可以考虑采用0.3.6新增加的zeromq传输方式。相对于GRE，zeromq的tcp传输是可靠的。但是目前0.3.6我们还没有正式支持windows，只在centos环境下编译测试过。

**Comment by muse117** [comment]
> 几百台同时部署的话有可能会出现丢包的情况，可以考虑采用0.3.6新增加的zeromq传输方式。相对于GRE，zeromq的tcp传输是可靠的。但是目前0.3.6我们还没有正式支持windows，只在centos环境下编译测试过。

好的，我研究一下，有问题再跟您请假，谢谢

**Comment by muse117** [comment]
> 几百台同时部署的话有可能会出现丢包的情况，可以考虑采用0.3.6新增加的zeromq传输方式。相对于GRE，zeromq的tcp传输是可靠的。但是目前0.3.6我们还没有正式支持windows，只在centos环境下编译测试过。

您当初为什么没用nanomsg呢？

**Comment by lcywoodlucy** [comment]
> > 几百台同时部署的话有可能会出现丢包的情况，可以考虑采用0.3.6新增加的zeromq传输方式。相对于GRE，zeromq的tcp传输是可靠的。但是目前0.3.6我们还没有正式支持windows，只在centos环境下编译测试过。
> 
> 我在windows下测试zeromq也是可以使用的啊，另外一个问题是，您当初为什么没用nanomsg呢？

主要是因为团队成员对zeromq比较熟悉，能很好的和我们目前工具链集成。我们准备在0.4版本支持插件功能，这样就能更好的支持不同的输出需求。

**Comment by muse117** [comment]
> > > 几百台同时部署的话有可能会出现丢包的情况，可以考虑采用0.3.6新增加的zeromq传输方式。相对于GRE，zeromq的tcp传输是可靠的。但是目前0.3.6我们还没有正式支持windows，只在centos环境下编译测试过。
> > 
> > 
> > 我在windows下测试zeromq也是可以使用的啊，另外一个问题是，您当初为什么没用nanomsg呢？
> 
> 主要是因为团队成员对zeromq比较熟悉，能很好的和我们目前工具链集成。我们准备在0.4版本支持插件功能，这样就能更好的支持不同的输出需求。

好的，期待0.4版本的发布
