### ISSUE TITLE
关于K8S流量监控

### ISSUE THREAD

**Issue by yingshang** [Netis/packet-agent#84]
大佬好，我看到docker目录的关于K8S流量监控，我使用了第一种方法，把服务启动起来，但是没有看到什么效果，还需要设置什么内容？

**Comment by lcywoodlucy** [comment]
k8s升级1.15.0(https://github.com/kubernetes/kubernetes/releases/tag/v1.15.0)之后kube-proxy中定义了更加严格的流量控制，缺省情况下不允许k8s的内网IP和外部IP直接通信，因此所有PKTG发送的GRE流量都被丢弃。
可以通过直接修改防火墙的方法使GRE流量正常发送到外部。
示例如下iptables -I FORWARD 1 -p gre -s 10.244.0.0/16 -d 10.1.6.64 -j ACCEPT
需要在k8s的node上添加，-s替换为实际的pod子网地址就，-d替换为BPC接受数据包的IP地址

**Comment by yingshang** [comment]
谢谢大佬，我试试

**Comment by NitroCao** [comment]
k8s 版本 1.19.7，网络插件试了 cilium 和 calico，加了这条规则也没有效果呢？在容器所在宿主机上抓物理网卡的流量的时候没有 GRE 协议数据包，后端也收不到 Pod 中 packet agent 发送的数据。
