### ISSUE TITLE
Can not recv message python-zmq

### ISSUE THREAD

**Issue by freeimust** [Netis/packet-agent#91]
Hi everyone, I have test packet-agent binary package with ubuntu14.04 [https://github.com/Netis/packet-agent/releases/download/v0.3.6/netis-packet-agent-0.3.6_amd64.deb](url)

first run pktminerg on 192.168.1.21

> pktminerg -i eth0 -r 192.168.1.25 -z 5555 -k 20

install python-zmq on 192.168.1.25

> sudo apt-get install python-zmq

run python zmq server with follow demo code

> import zmq
context = zmq.Context()
socket = context.socket(zmq.REP)
socket.bind("tcp://*:5555")
while True:
    message = socket.recv_string()
    print(message)
    socket.send_string("OK, 200")

but 192.168.1.25 can not recv any message, I am sure firewall is close

**Comment by jacknetis** [comment]
use zmq.PULL and socket.recv().
ref this https://github.com/Netis/packet-agent/blob/master/scripts/recvzmq/recvzmq.py
