### ISSUE TITLE
ScopeGuard这个类是什么作用呢？

### ISSUE THREAD

**Issue by muse117** [Netis/packet-agent#92]
您好，请教一个技术问题， ScopeGuard这个类没看懂这个类起什么作用？

**Comment by lcywoodlucy** [comment]
主要用在资源管理上，防止使用资源的函数异常返回导致资源无法正常释放

**Comment by muse117** [comment]
还有一个问题，您是用cmake生成Makefile的，如果我先引入一个别的库是不是需要修改CMakeLists.txt加入该库的链接，不能直接修改Makefile吧
